Implement SimpleBeanDefinitionRegistry with tests (#18)
bobocode-breskul/bring pull request #35
Opened 2023-11-11 08:07 UTC by RomanPryshchepa

2023-11-11 13:12 UTC, JoshukLite requested changes

2023-11-11 13:12 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  private BeanDefinitionRegistry beanDefinitionRegistry;
I would recommend using here implementation class, not the interface because here is tested a class, not the interface,

2023-11-11 13:12 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +    assertTrue(actualMessage.contains(expectedMessage));
Why do you test it by `contains` method? Aren't messages should be tested for equality?

2023-11-11 13:12 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +    beanDefinitionRegistry.removeBeanDefinition("testBeanName");
What is the point of this action here? If you are testing behavior on unexisting bean name removal, then I assume it's better to do as separate test.

2023-11-11 13:12 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +    assertThat(beanDefinitionNames).contains("testBeanName1", "testBeanName2");
These two lines could be shortened by using `assertThat(beanDefinitionNames).containsExactlyInAnyOrder("testBeanName1", "testBeanName2");`

2023-11-11 13:12 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  void whenRegisterBeanDefinitionsThenGetRegisteredBeanDefinitionCount() {
I would advice writing one more test to check the count after bean definition removal.

2023-11-11 16:30 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +/*
Is it supposed to left here? 
Looks like copy-paste from ticket description

2023-11-11 16:30 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +    Set<String> beanDefinitionNamesSet = beanDefinitionMap.keySet();
You can make use of Collection interface method `toArray()` here. 
For example:
```return beanDefinitionMap.keySet().toArray(String[]::new);```

2023-11-11 16:30 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
>    public boolean containsBeanDefinition(String beanName) {
What will happen if I pass the null value here?

2023-11-13 00:05 UTC, s-barabash commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +      beanDefinitionMap.put(beanName, beanDefinition);
It will throw NullPointerException if the specified key or value is null, it is a limitation of ConcurrentHashMap. We should handle these cases

2023-11-13 00:05 UTC, s-barabash commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
>    @Override
Will we implement this method?

2023-11-13 00:05 UTC, s-barabash commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  void givenBeanNameAndBeanDefinitionWhenBeanDefinitionNotRegisterThenRegisterBeanDefinition() {
let's use underscore to split given_when_then for example:
`givenBeanNameAndBeanDefinition_whenBeanDefinitionNotRegister_thenRegisterBeanDefinition`

2023-11-13 00:05 UTC, s-barabash commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +          "Cannot registered a beanDefinition with name %s because a beanDefinition with that name is already registered%n".formatted(
Let's create constant for this template

2023-11-13 00:05 UTC, s-barabash commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +    } else {
NIT: it is not important to have else clause if in if statement you throw the error or return the value

2023-11-13 00:05 UTC, s-barabash commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  @Test()
you can remove this ()

2023-11-13 00:05 UTC, s-barabash commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  void givenBeanNameAndBeanDefinitionWhenBeanDefinitionRegisterDuplicateThenThrow() {
NIT: ThenThrowBeanDefinitionDuplicateException

2023-11-13 00:05 UTC, s-barabash commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  void givenBeanNameThenRemoveBeanDefinition() {
you are missing **when**, so it is not clear what are you testing here

2023-11-13 00:05 UTC, s-barabash commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
>    public void removeBeanDefinition(String beanName) throws NoSuchBeanDefinitionException {
In which cases you will throw NoSuchBeanDefinitionException? Should we keep this signature?

2023-11-13 00:05 UTC, s-barabash commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
>    public BeanDefinition getBeanDefinition(String beanName) throws NoSuchBeanDefinitionException {
In which cases you will throw NoSuchBeanDefinitionException? Should we keep this signature?

2023-11-13 00:05 UTC, s-barabash commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  void givenBeanNameThenGetBeanDefinition() {
you are missing when, so it is not clear what are you testing here

2023-11-13 00:05 UTC, s-barabash commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  void givenBeanNameThenContainsBeanDefinition() {
you are missing when, so it is not clear what are you testing here

2023-11-13 17:49 UTC, AlexandrKarpachov commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
>    public String[] getBeanDefinitionNames() {
Why do we want to return here array? Maybe Collection would be better?

2023-11-14 06:45 UTC, OlehYakovenko commented on pom.xml
> +      <organization>PE Roman Pryshchepa</organization>
Test comment. What is PE ?

2023-11-14 06:50 UTC, RomanPryshchepa commented on pom.xml
> +      <organization>PE Roman Pryshchepa</organization>
Private entrepreneur

2023-11-15 13:05 UTC, golichenko02 approved these changes
Good job! Left a few minor comments

2023-11-15 13:05 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +    for (Entry<String, String> entry : aliasMap.entrySet()) {
Don't you think about declarative way of doing it or you just don't like it?:)
E.g.
```
return aliasMap.entrySet().stream()
        .filter(entry -> name.equals(entry.getValue()))
        .map(Entry::getKey)
        .collect(Collectors.toSet());
```

2023-11-15 13:05 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/exception/BeanDefinitionDuplicateException.java
> +
I'd suggest to add small javadoc when this exception is thrown

2023-11-15 13:05 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/exception/AliasDuplicateException.java
> +public class AliasDuplicateException extends RuntimeException {
I'd suggest to add small javadoc when this exception is thrown

2023-11-15 13:41 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +        SimpleBeanDefinitionRegistryTest.TEST_ALIAS);
No need to provide class for the constant.

2023-11-15 13:41 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +        TEST_BEAN_NAME_2, SimpleBeanDefinitionRegistryTest.TEST_ALIAS));
Same as above.

2023-11-15 13:41 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +        SimpleBeanDefinitionRegistryTest.TEST_ALIAS);
Same as above.

2023-11-15 13:41 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +  void given_BeanNameAndAlias_When_RegisterAliasWithNullName_Then_ThrowNoSuchBeanDefinitionException() {
Method name (`Then_ThrowNoSuchBeanDefinitionException`) does not correspond to what it really tests.

Please modify name for all methods where title ends with `ThrowNoSuchBeanDefinitionException` but in reality there is other exception is thrown.

2023-11-15 13:41 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +    assertThat(simpleBeanDefinitionRegistry.getAliases(TEST_BEAN_NAME_1)).as("")
Empty `.as("")` method call.

2023-11-15 13:41 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +    assertThat(simpleBeanDefinitionRegistry.getAliases(TEST_BEAN_NAME_2)).as("")
Same as above.

2023-11-15 13:41 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +        TEST_ALIAS_1, TEST_ALIAS_2);
Please format it so `.containsExactlyInAnyOrder(...)` would be on the new line.

2023-11-15 13:41 UTC, JoshukLite commented on src/test/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistryTest.java
> +//    BeanDefinition beanDefinitionMock2 = Mockito.mock(BeanDefinition.class);
Is there any reason to hold this commented section?

2023-11-15 15:16 UTC, golichenko02 approved these changes

2023-11-15 15:40 UTC, JoshukLite approved these changes

2023-11-15 17:37 UTC, merged