Logs to the ScanUtils
bobocode-breskul/bring pull request #63
Opened 2023-11-16 11:18 UTC by OlehYakovenko

added logging to the ScanUtils.class

2023-11-16 18:13 UTC, AlexandrKarpachov requested changes

2023-11-16 18:13 UTC, AlexandrKarpachov commented on src/main/java/io/github/bobocodebreskul/context/scan/utils/ScanUtilsImpl.java
> +        filter, packagePath);
filter - we will print predicate class name and it's not informative, so it's better.not to write it here.

2023-11-16 18:13 UTC, AlexandrKarpachov commented on src/main/java/io/github/bobocodebreskul/context/scan/utils/ScanUtilsImpl.java
> +      throw new IllegalArgumentException(
missed . symbol at the end

2023-11-16 18:13 UTC, AlexandrKarpachov commented on src/main/java/io/github/bobocodebreskul/context/scan/utils/ScanUtilsImpl.java
> +          "Package name must not contain illegal symbols");
Unreachable code - if a package contains illegal symbols it will throw in the previous if statement.

2023-11-16 20:45 UTC, JoshukLite commented
I assume this PR has dependency on `feature/45-scanutils-validation` branch as i can see here exactly same code changes as in the mentioned branch. 
Let's close first branch `feature/45-scanutils-validation` and then move on to this PR after dev merge into this branch.

2023-11-17 18:56 UTC, AlexandrKarpachov requested changes

2023-11-17 18:56 UTC, AlexandrKarpachov commented on src/main/java/io/github/bobocodebreskul/context/scan/utils/ScanUtilsImpl.java
> +      log.error("Package name must contain only letters, numbers and symbols");
and symbol [.]

2023-11-17 19:05 UTC, AlexandrKarpachov approved these changes

2023-11-17 19:10 UTC, JoshukLite approved these changes

2023-11-17 19:10 UTC, merged

2023-11-17 19:31 UTC, s-barabash approved these changes