add logging to SimpleBeanDefinitionRegistry
bobocode-breskul/bring pull request #80
Opened 2023-11-21 18:23 UTC by RomanPryshchepa

2023-11-21 18:47 UTC, golichenko02 requested changes
There's a lot of duplicated messages for different log levels, which may produce a confusion to the end user

2023-11-21 18:47 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +    log.trace("Getting all bean definition names");
Please choose single level for the same log message, since when end user will setup trace level, he will see duplicated messages for each log level

2023-11-21 18:47 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +    log.trace("Getting bean definition count");
the same as above, duplicated messages

2023-11-21 18:47 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +    log.trace("Checking is the beanName {} in use", beanName);
duplicated message

2023-11-21 18:47 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/context/registry/SimpleBeanDefinitionRegistry.java
> +    log.trace("Getting all bean definition");
duplicated messages

2023-11-23 17:15 UTC, IIUPAMET approved these changes

2023-11-23 19:42 UTC, JoshukLite approved these changes

2023-11-23 20:26 UTC, golichenko02 approved these changes

2023-11-23 20:52 UTC, merged