#91 implement code logic
bobocode-breskul/bring pull request #97
Opened 2023-11-29 17:05 UTC by s-barabash

2023-11-29 18:31 UTC, JoshukLite commented on src/main/java/io/github/bobocodebreskul/server/DispatcherServlet.java
> +      if (ex instanceof InvocationTargetException) {
I believe pattern matching could be used here

2023-11-29 18:31 UTC, JoshukLite commented on src/main/java/io/github/bobocodebreskul/server/WebErrorHandlerControllerScanner.java
> +            .count() != 1) {
What is expectation of this? Is it expected that user can inject `HttpServletRequest` into his error handling method?
If yes, then method `isInstatnce(HttpServletRequest.class` doesn't when HttpServletRequest object is injected to error handling method.

2023-11-29 18:40 UTC, JoshukLite commented on src/main/java/io/github/bobocodebreskul/server/WebErrorHandlerControllerScanner.java
> +    if (methodParameterTypes.length == 2 && methodParameterTypes[0].isInstance(Throwable.class)) {
It seems that any exception class will fail `.isInstance(Throwable.class)` check, so this method will return always 2nd argument if error handling method has 2 parameters.

2023-11-29 18:54 UTC, AlexandrKarpachov requested changes

2023-11-29 18:54 UTC, AlexandrKarpachov commented on src/main/java/io/github/bobocodebreskul/context/annotations/ExceptionHandler.java
> + *
twice writed ErrorHandlerController looks like a typo.

2023-11-29 18:54 UTC, AlexandrKarpachov commented on src/main/java/io/github/bobocodebreskul/server/DispatcherServlet.java
>    }
Need to take into account that user can set arguments in different order.

2023-11-30 07:00 UTC, AlexandrKarpachov approved these changes

2023-11-30 07:46 UTC, IIUPAMET approved these changes

2023-11-30 11:52 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/server/WebErrorHandlerControllerScanner.java
> +      throw new MethodValidationException("Invalid parameter quantaty");
```
throw new MethodValidationException("Invalid parameter quantity");
```

2023-11-30 12:02 UTC, golichenko02 commented on src/main/java/io/github/bobocodebreskul/server/WebErrorHandlerControllerScanner.java
> +      throw new MethodValidationException("Only 1 exceptions is allowed for errorhandler method");
```suggestion
throw new MethodValidationException("Only 1 exception is allowed for the error handler method");
```

2023-11-30 12:02 UTC, golichenko02 reviewed
Good job! Left minor comments

2023-12-01 07:41 UTC, merged